### ISSUE TITLE
Social Icons are hidden

### ISSUE THREAD

**Issue by techmannih** [CrowdDotDev/crowd.dev#1628] opened 2023-10-05 02:44 UTC
### crowd.dev edition

Community (self hosted)

### What happened?

Hello @joanagmaia ,
I found an issue in your website in which social icons are hidden for entire pixels.Only Github icon is show, rest all icon like twitter , youtube , discord and linkedin are not shown.  
so I want to on this issue .... please assign me 
![2023-10-05_08-10](https://github.com/CrowdDotDev/crowd.dev/assets/125847751/d3d0ba1f-d212-491c-83e3-27d9a6f85b84)

**Comment by CrypticRevenger** [comment] 2023-10-05 14:23
@joanagmaia Please assign me, I want to do it.

**Comment by AnishTiwari16** [comment] 2023-10-06 14:18
will fix it please assign it to me!

**Comment by joanagmaia** [comment] 2023-10-11 09:01
@AnishTiwari16 closing this issue! Since you mentioned it is working fine and I also wasn't able to reproduce 😄

**Closed by joanagmaia** 2023-10-11 09:01 UTC
