### ISSUE TITLE
[C-1325] Home: PR Conversations with team members only shouldn't be displayed

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#836] opened 2023-05-08 12:12 UTC
**Problem**

It seems like PR conversations are showing on Home ("trending conversations") even if only team member participated. 

![Bildschirmfoto 2023-05-08 um 08.10.13.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/8fccf961-4cc4-4010-b205-ce3ef61085f6/56740065-8627-4706-94e5-a02e1f95a3a3)

**Expected behavior**

Conversations where only members with "team members = true" participated should not be displayed on Home.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1325](https://linear.app/crowddotdev/issue/C-1325/home-pr-conversations-with-team-members-only-shouldnt-be-displayed)</sub>

**Comment by peoray** [comment] 2023-05-08 15:15
@jonathimer how do I reproduce this?

**Comment by peoray** [comment] 2023-05-08 19:59
@jonathimer thank you
I'm assuming I'll have to create API keys for this right?

Where can I find which keys to use? env file? backend?

**Comment by jonathimer** [comment] 2023-05-09 19:04
not sure if you need an API key for this

cc @joanreyero - can you help out?

**Comment by joanreyero** [comment] 2023-05-25 10:23
Hey @peoray! Sorry, I missed this. You should be able to replicate with the sample data. Simply mark the members as team members.

**Comment by joanagmaia** [comment] 2023-08-24 13:39
Duplicate of this one [C-995](https://linear.app/crowddotdev/issue/C-995/home-conversations-of-team-members-only-shouldnt-be-displayed), will cancel it

**Closed by joanagmaia** 2023-08-24 13:39 UTC
Labels: Improvement, Medium priority
